**Applications of Proximal Policy Optimization Algorithm on Atari Games**

Rosaline Zhu, Stanley Araki

**Import libraries to use**

In [32]:
import gym
import numpy as np
import torch
from torch import nn
from torch import optim
import ale_py

In [33]:
# import ray
# from ray import tune
# from ray.rllib.agents.dqn import DQNTrainer

# ray.shutdown()
# ray.init(include_webui=False, ignore_reinit_error=True)

# ENV = "Breakout-ramDeterministic-v4"
# TARGET_REWARD = 200
# TRAINER = DQNTrainer

# tune.run(
#     TRAINER,
#     stop={"episode_reward_mean": TARGET_REWARD},
#     config={
#       "env": ENV,
#       "monitor": True,
#       "evaluation_num_episodes": 25,
#       "double_q": True,
#       "hiddens": [128],
#       "num_workers": 0,
#       "num_gpus": 1,
#       "target_network_update_freq": 12_000,
#       "lr": 5E-6,
#       "adam_epsilon": 1E-5,
#       "learning_starts": 150_000,
#       "buffer_size": 1_500_000,
#     }
# )

**Set up environment for Atari Game**

In [36]:
# import pyvirtualdisplay
# _display = pyvirtualdisplay.Display(visible=False, size=(1400, 900))
# _ = _display.start()

# import ray
# from ray import tune
# from ray.rllib.agents.ppo import PPOTrainer

# ray.shutdown()
# ray.init(include_webui=False, ignore_reinit_error=True)

# import numpy as np
# import gym
# from gym.wrappers import TransformObservation
# from gym.spaces import Box
# from ray.tune.registry import register_env
# from gym import ObservationWrapper


# class TruncateObservation(ObservationWrapper):
#   interesting_columns = [70, 71, 72, 74, 75, 90, 94, 95, 99, 101, 103, 105, 119]

#   def __init__(self, env):
#     super().__init__(env)
#     self.observation_space = Box(low=0, high=255, shape=(len(self.interesting_columns),), dtype=np.uint8)

#   def observation(self, obs):
#     # print(obs.tolist())  # print full observation to find interesting columns
#     return obs[self.interesting_columns]  # filter


# def env_creator(env_config):
#     env = gym.make('Breakout-ramDeterministic-v4')
#     env = TruncateObservation(env)
#     return env


# register_env("simpler_breakout", env_creator)
# ENV = "simpler_breakout"
# TARGET_REWARD = 200
# TRAINER = PPOTrainer


# tune.run(
#     TRAINER,
#     stop={"episode_reward_mean": TARGET_REWARD},
#     config={
#       "env": ENV,
#       "num_workers": 1,
#       "num_gpus": 0,
#       "monitor": True,
#       "evaluation_num_episodes": 25
#     }
# )

In [37]:
env = gym.make('CartPole-v1')
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break
env.close()

[ 0.03928695  0.04637473 -0.03558441  0.00541142]
[ 0.04021444 -0.1482193  -0.03547618  0.28665808]
[ 0.03725005  0.04739015 -0.02974302 -0.0169993 ]
[ 0.03819786  0.24292575 -0.030083   -0.3189161 ]
[ 0.04305637  0.43846294 -0.03646133 -0.6209323 ]
[ 0.05182563  0.24386865 -0.04887997 -0.33995208]
[ 0.056703    0.43965077 -0.05567901 -0.6476395 ]
[ 0.06549602  0.63550246 -0.06863181 -0.95732296]
[ 0.07820607  0.83147687 -0.08777826 -1.2707543 ]
[ 0.09483561  1.0276028  -0.11319335 -1.5895844 ]
[ 0.11538766  1.2238727  -0.14498504 -1.9153129 ]
[ 0.13986512  1.0305791  -0.1832913  -1.670891  ]
Episode finished after 12 timesteps
[ 0.0186473   0.01327605 -0.02824574  0.02536218]
[ 0.01891282 -0.18142968 -0.02773849  0.30900115]
[ 0.01528423  0.01407629 -0.02155847  0.00770093]
[ 0.01556575  0.20950067 -0.02140445 -0.29170525]
[ 0.01975576  0.01469035 -0.02723856 -0.00584912]
[ 0.02004957 -0.18003058 -0.02735554  0.2781168 ]
[ 0.01644896 -0.3747518  -0.02179321  0.56204784]
[ 0.00895392 -

**Set up Proximal Policy Optimization Algorithm**