**Applications of Proximal Policy Optimization Algorithm on Atari Games**

Rosaline Zhu, Stanley Araki

**Import libraries to use**

In [32]:
import gym
import numpy as np
import torch
from torch import nn
from torch import optim
import ale_py

In [33]:
# import ray
# from ray import tune
# from ray.rllib.agents.dqn import DQNTrainer

# ray.shutdown()
# ray.init(include_webui=False, ignore_reinit_error=True)

# ENV = "Breakout-ramDeterministic-v4"
# TARGET_REWARD = 200
# TRAINER = DQNTrainer

# tune.run(
#     TRAINER,
#     stop={"episode_reward_mean": TARGET_REWARD},
#     config={
#       "env": ENV,
#       "monitor": True,
#       "evaluation_num_episodes": 25,
#       "double_q": True,
#       "hiddens": [128],
#       "num_workers": 0,
#       "num_gpus": 1,
#       "target_network_update_freq": 12_000,
#       "lr": 5E-6,
#       "adam_epsilon": 1E-5,
#       "learning_starts": 150_000,
#       "buffer_size": 1_500_000,
#     }
# )

**Set up environment for Atari Game**

In [36]:
# import pyvirtualdisplay
# _display = pyvirtualdisplay.Display(visible=False, size=(1400, 900))
# _ = _display.start()

# import ray
# from ray import tune
# from ray.rllib.agents.ppo import PPOTrainer

# ray.shutdown()
# ray.init(include_webui=False, ignore_reinit_error=True)

# import numpy as np
# import gym
# from gym.wrappers import TransformObservation
# from gym.spaces import Box
# from ray.tune.registry import register_env
# from gym import ObservationWrapper


# class TruncateObservation(ObservationWrapper):
#   interesting_columns = [70, 71, 72, 74, 75, 90, 94, 95, 99, 101, 103, 105, 119]

#   def __init__(self, env):
#     super().__init__(env)
#     self.observation_space = Box(low=0, high=255, shape=(len(self.interesting_columns),), dtype=np.uint8)

#   def observation(self, obs):
#     # print(obs.tolist())  # print full observation to find interesting columns
#     return obs[self.interesting_columns]  # filter


# def env_creator(env_config):
#     env = gym.make('Breakout-ramDeterministic-v4')
#     env = TruncateObservation(env)
#     return env


# register_env("simpler_breakout", env_creator)
# ENV = "simpler_breakout"
# TARGET_REWARD = 200
# TRAINER = PPOTrainer


# tune.run(
#     TRAINER,
#     stop={"episode_reward_mean": TARGET_REWARD},
#     config={
#       "env": ENV,
#       "num_workers": 1,
#       "num_gpus": 0,
#       "monitor": True,
#       "evaluation_num_episodes": 25
#     }
# )

In [40]:
env = gym.make('CartPole-v1')
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break
env.close()

[-0.03266798 -0.0335794  -0.03070569  0.0044753 ]
[-0.03333957 -0.22824784 -0.03061619  0.28731427]
[-0.03790453 -0.03270295 -0.0248699  -0.01486536]
[-0.03855858 -0.22745958 -0.02516721  0.26986822]
[-0.04310778 -0.4222135  -0.01976984  0.5545082 ]
[-0.05155205 -0.22681962 -0.00867968  0.25566274]
[-0.05608844 -0.4218166  -0.00356642  0.54559535]
[-0.06452477 -0.2266447   0.00734548  0.25179085]
[-0.06905767 -0.0316284   0.0123813  -0.03856613]
[-0.06969023  0.16331384  0.01160998 -0.32731706]
[-0.06642395 -0.03197147  0.00506364 -0.0309956 ]
[-0.06706338 -0.22716567  0.00444372  0.26328066]
[-0.0716067  -0.42235076  0.00970934  0.55736184]
[-0.08005371 -0.61760765  0.02085657  0.8530879 ]
[-0.09240586 -0.42277613  0.03791833  0.56703556]
[-0.10086139 -0.6184089   0.04925904  0.8714191 ]
[-0.11322957 -0.42399028  0.06668743  0.5946212 ]
[-0.12170937 -0.6199791   0.07857985  0.9075426 ]
[-0.13410896 -0.81607187  0.0967307   1.2238528 ]
[-0.1504304  -1.0122974   0.12120776  1.5452095 ]


**Set up Proximal Policy Optimization Algorithm**